apiVersion: apps/v1
kind: Deployment
metadata:
  name: ullis-argocd-deployment
  labels:
    app: nginx          # used by the service selector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:             # configuration, of a pod
      labels:
        app: nginx        # used by the servoce selector
    spec:                 # blueprint for a pod
      containers:
      - name: nginx
        image: devops2022.azurecr.io/ullis-image:f8ab7a529dab7d82bd1755c440abd001dc64f498
        ports:
        - containerPort: 80   # should match targetPort in Service
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata: 
  name: ullis-ingess-clusterip
spec: 
  # tls: ... da kommt das Zertifikat rein sp√§ter
  selector: 
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
